let homes = [
    {
        id: 1,
        title: 'Buyuk Ipak Yo\'li 2/1/4!',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/197fqwxgnmap-UZ/image;s=644x461',
        price: [22500],
        date: 1632548072000,
        address: 'Toshkent, Mirzo-Ulug‘bek tumani',
        numberOfRooms: [2],
        floor: [4],
        square: [71],
        type: ['Family', 'Student'],
        info: 'Yaqinida joylashgan: Kasalxona, poliklinika, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar, Park, yashil zona, Koʻngilochar muassasalar, Restoran, kafelar, turargoh, Supermarket, doʻkonlar',
    },
    {
        id: 2,
        title: '3 xonali uy sotiladi!',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/nj9pscfczma62-UZ/image;s=1000x700',
        price: [25000],
        date: 1631770472000,
        address: 'Guliston',
        numberOfRooms: [3],
        floor: [3],
        square: [70],
        type: ['Family', 'Tourist'],
        info: 'Yaqinida joylashgan: Kasalxona, poliklinika, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar, Park, sariq zona; Kvartirada bor: Internet, Telefon, Muzlatkich, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon'
    },
    {
        id: 3,
        title: '3 xonali 1 qavat kvartira!',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/20aj5iemjxoq3-UZ/image;s=1000x700',
        price: [38000],
        date: 1632513782000,
        address: 'Navoiy',
        numberOfRooms: [3],
        floor: [1],
        square: [65],
        type: ['Family', 'Tourist'],
        info: 'Yaqinida joylashgan: Kasalxona, poliklinika, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar; Kvartirada bor: Internet, Telefon, Muzlatkich, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon'
    },
    {
        id: 4,
        title: 'Gagarin MCHJ 3/3/6!',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/pm80n8cvee6p2-UZ/image;s=1000x700',
        price: [82000],
        date: 1632513782000,
        address: 'Toshkent',
        numberOfRooms: [3],
        floor: [3],
        square: [86],
        type: ['Family', 'Tourist'],
        info: 'Yaqinida joylashgan: Kasalxona, poliklinika, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar; Kvartirada bor: Internet, Telefon, Muzlatkich, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon'
    },
    {
        id: 5,
        title: 'Maksim Gorkiy kvartira',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/4f9rawcz17pi1-UZ/image;s=1000x700',
        price: [45000],
        date: 1632805382000,
        address: 'Toshkent',
        numberOfRooms: [2],
        floor: [2],
        square: [56],
        type: ['Family', 'Tourist'],
        info: 'Yaqinida joylashgan: Kasalxona, poliklinika, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar; Kvartirada bor: Internet, Telefon, Muzlatkich, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon'
    },
    {
        id: 6,
        title: 'Arenda kvartira 1/14/16',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/8h721x3x0sii3-UZ/image;s=1000x700',
        price: [300],
        date: 1632805382000,
        address: 'Toshkent',
        numberOfRooms: [1],
        floor: [14],
        square: [45],
        type: ['Family', 'Student', 'Rent'],
        info: 'Yaqinida joylashgan: Kasalxona, poliklinika, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar; Kvartirada bor: Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona,'
    },
    {
        id: 7,
        title: 'Xamza Metro kvartira (Golden House)',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/wb1zoedmoimh2-UZ/image;s=1000x700',
        price: [700],
        date: 1632718982000,
        address: 'Toshkent, Xamza metro',
        numberOfRooms: [2],
        floor: [4],
        square: [70],
        type: ['Family', 'Student', 'Tourist', 'Rent'],
        info: 'Yaqinida joylashgan: Kasalxona, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar; Kvartirada bor: Internet, Telefon, Muzlatkich, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon'
    },
    {
        id: 8,
        title: 'Shota Rustaveli 2/2/4',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/shv3lzdzm27x-UZ/image;s=1000x700',
        price: [450],
        date: 1632718912000,
        address: 'Toshkent, Yakkasaroy',
        numberOfRooms: [2],
        floor: [2],
        square: [60],
        type: ['Student', 'Tourist', 'Rent'],
        info: 'Yaqinida joylashgan: Kasalxona, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar; Kvartirada bor: Internet, Telefon, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon'
    },
    {
        id: 9,
        title: '2 xonali uy sotiladi!',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/in15yiqcxjzy1-UZ/image;s=1000x700',
        price: [35500],
        date: 1632286982000,
        address: 'Toshkent, Yashnabod tumani',
        numberOfRooms: [2],
        floor: [8],
        square: [62],
        type: ['Family', 'Tourist'],
        info: 'Yaqinida joylashgan: Kasalxona, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar; Kvartirada bor: Internet, Telefon, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon'
    },
    {
        id: 10,
        title: 'Chilonzor-10 2/2/4',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/dmlqzddpm1a81-UZ/image;s=1000x700',
        price: [29000],
        date: 1632805382000,
        address: 'Toshkent, Chilonzor-10',
        numberOfRooms: [2],
        floor: [4],
        square: [45],
        type: ['Family', 'Student'],
        info: 'Yaqinida joylashgan: Kasalxona, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar; Kvartirada bor: Internet, Telefon, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon'
    },
    {
        id: 11,
        title: 'Yashnabot tumani Tuzel 1',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/qviggfc0wtbn1-UZ/image;s=1000x700',
        price: [29000],
        date: 1632286982000,
        address: 'Toshkent, Yashnabod tumani',
        numberOfRooms: [2],
        floor: [3],
        square: [53],
        type: ['Family', 'Student'],
        info: 'Yaqinida joylashgan: Kasalxona, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar; Kvartirada bor: Internet, Telefon, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon'
    },
    {
        id: 12,
        title: '4 xonali uy sotiladi',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/w61cu2leje5d-UZ/image;s=1000x700',
        price: [48000],
        date: 1632114182000,
        address: 'Samarqand',
        numberOfRooms: [4],
        floor: [2],
        square: [65],
        type: ['Tourist', 'Student'],
        info: 'Yaqinida joylashgan: Kasalxona, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar; Kvartirada bor: Internet, Telefon, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon'
    },
    {
        id: 13,
        title: 'Kvartira sotiladi Chilonzor 19',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/c0ern1reuwch-UZ/image;s=1000x700',
        price: [34500],
        date: 1632286982000,
        address: 'Toshkent Chilonzor 19',
        numberOfRooms: [2],
        floor: [3],
        square: [46],
        type: ['Family', 'Tourist'],
        info: 'Yaqinida joylashgan: Kasalxona, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar; Kvartirada bor: Internet, Telefon, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon'
    },
    {
        id: 14,
        title: '3 xonali kvartira Chilonzor 11',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/axbnlzpnx7ww2-UZ/image;s=1000x700',
        price: [42000],
        date: 1632718912000,
        address: 'Toshkent Chilonzor 11',
        numberOfRooms: [3],
        floor: [3],
        square: [63],
        type: ['Family', 'Tourist'],
        info: 'Yaqinida joylashgan: Kasalxona, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar; Kvartirada bor: Internet, Telefon, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon'
    },
    {
        id: 15,
        title: 'Kunlik kvartira 3 xonali',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/o414k4y4w4t93-UZ/image;s=1000x700',
        price: [30],
        date: 1631941382000,
        address: 'Buxoro',
        numberOfRooms: [3],
        floor: [2],
        square: [65],
        type: ['Student', 'Daily'],
        info: 'Yaqinida joylashgan: Kasalxona, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar; Kvartirada bor: Internet, Telefon, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon'
    },
    {
        id: 16,
        title: 'Chilonzorda kunlik kvartira',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/ssad4y3l2vid1-UZ/image;s=1000x700',
        price: [25],
        date: 1632027782000,
        address: 'Toshkent, Chilonzor tumani',
        numberOfRooms: [2],
        floor: [2],
        square: [40],
        type: ['Daily'],
        info: 'Yaqinida joylashgan: Kasalxona, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar; Kvartirada bor: Internet, Telefon, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon'
    },
    {
        id: 17,
        title: 'Yevro kv (Shahar markazida)',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/9qvud60ard3b1-UZ/image;s=1000x700',
        price: [650],
        date: 1632718912000,
        address: 'Toshkent, Yakkasaroy tumani',
        numberOfRooms: [2],
        floor: [5],
        square: [65],
        type: ['Family', 'Rent', 'Student'],
        info: 'Yaqinida joylashgan: Kasalxona, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar; Kvartirada bor: Internet, Telefon, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon'
    },
    {
        id: 18,
        title: 'Kunlik kvartira',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/pz1kuif8gvje1-UZ/image;s=1000x700',
        price: [20],
        date: 1632513782000,
        address: 'Toshkent, Uchtepa tumani',
        numberOfRooms: [2],
        floor: [2],
        square: [96],
        type: ['Daily', 'Student'],
        info: 'Yaqinida joylashgan: Kasalxona, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar; Kvartirada bor: Internet, Telefon, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon'
    },
    {
        id: 19,
        title: '2 xonali kvartira ijaraga',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/c0djcszgcquv1-UZ/image;s=1000x700',
        price: [600],
        date: 1631853832000,
        address: 'Toshkent, Mirzo Ulug\'bek tumani',
        numberOfRooms: [2],
        floor: [2],
        square: [60],
        type: ['Rent', 'Student'],
        info: 'Yaqinida joylashgan: Kasalxona, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar; Kvartirada bor: Internet, Telefon, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona, Balkon'
    },
    {
        id: 20,
        title: 'DOM Katej 125 kv',
        img: 'https://apollo-olx.cdnvideo.ru/v1/files/xhyjtj3quf25-UZ/image;s=1000x700',
        price: [95000],
        date: 1632631432000,
        address: 'Toshkent, Shayhontohur tumani',
        numberOfRooms: [4],
        floor: [1],
        square: [125],
        type: ['Family'],
        info: 'Yaqinida joylashgan: Kasalxona, Maktab, Bolalar maydonchasi, Bolalar bogʻchasi, Bekatlar; Kvartirada bor: Internet, Telefon, Televizor, Konditsioner, Kabelli TV, Kir yuvish mashinasi, Oshxona'
    }
];